name: Build
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build XCFramework
    runs-on: macos-latest
    env:
      PACKAGE_NAME: RunveyKit
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build XCFramework
        run: |
          sh ./.github/build.sh $PACKAGE_NAME
      - name: Create Zip
        run: zip -r ./${{ env.PACKAGE_NAME }}.xcframework.zip ./${{ env.PACKAGE_NAME }}.xcframework
      - name: Upload artifact to Emerge
        uses: EmergeTools/emerge-upload-action@v1.1.0
        with:
          build_type: release
          artifact_path: ./${{ env.PACKAGE_NAME }}.xcframework.zip
          emerge_api_key: ${{ secrets.EMERGE_API_KEY }}
